# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcBK-WUEn5FZIes7uvmAhn71qjCmx08S
"""

import numpy as np

def preprocess_image(image):
    """
    Normalize the image pixel values to the range [0, 1].
    """
    return (image - np.min(image)) / (np.max(image) - np.min(image))

import numpy as np

def low_intensity_membership(x):
    return np.maximum(0, 1 - 2 * x)

def medium_intensity_membership(x):
    return np.maximum(0, 1 - 2 * np.abs(x - 0.5))

def high_intensity_membership(x):
    return np.maximum(0, 2 * x - 1)

def fuzzify_image(image):
    """
    Apply fuzzification functions to the input image.
    """
    low = low_intensity_membership(image)
    medium = medium_intensity_membership(image)
    high = high_intensity_membership(image)
    return np.stack([low, medium, high], axis=0)